import Head from "next/head";

export default function Blog() {
  return (
    <>
      <Head>
        <title>Create Next Apps</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>yapım aşamasında</div>
    </>
  );
}
